---
- name: create instance
  hosts: localhost
  gather_facts: false
  become: yes
  tasks:
  - name: Create app1
    include_role:
      name: roles/osp_create_instances
      vars_from: app1
  
  - name: Create app2
    include_role:
      name: roles/osp_create_instances
      vars_from: app2

  - name: Create frontend
    include_role:
      name: roles/osp_create_instances
      vars_from: frontend

  - name: Create db
    include_role:
      name: roles/osp_create_instances
      vars_from: db
